### ISSUE TITLE
skip_subtrees

### ISSUE THREAD

**Issue by iamkrish73** [robshakir/pyangbind#107]
Hi Rob,

I have problems while specifying a list for skip_subtree while using with dumps.  I did not find any examples in the tests directory.  Appreciate if you can point me to some example on how to use this.

Thanks,
Krish

**Comment by iamkrish73** [comment]
I modified the tests/serialise/json-serialise/run.py like this:

#pybind_json = json.loads(dumps(js))
pybind_json = json.loads(dumps(js, skip_subtrees=js.c1.l1))

I get the following error:
---
Traceback (most recent call last):
  File "./run.py", line 126, in <module>
    main()
  File "./run.py", line 94, in main
    pybind_json = json.loads(dumps(js, skip_subtrees=js.c1.l1))
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/pybindJSON.py", line 104, in dumps
    raise AttributeError('the subtrees to be skipped should be a list')
AttributeError: the subtrees to be skipped should be a list
---

**Comment by robshakir** [comment]
Hi Krish,

`skip_subtrees` expects a list of the paths that should be skipped. So, for example, if you are serialising "/foo/bar/a/b/c" you can provide "/foo/bar/a/b/d" and the "d" subtree will be excluded from the b object.

Thanks,
r.

**Comment by JoseIgnacioTamayo** [comment]
Closing issues with no recent activity
