### ISSUE TITLE
openconfig-bgp.yang serializing to json fails 

### ISSUE THREAD

**Issue by sanabby** [robshakir/pyangbind#109]
Generation of python classes for openconfig-bgp yang model works fine.

Initializing the BGP objects from generated classes and serializing it to json fails. This is because of the following traceback which shows AttributeError: Unmapped type.

Traceback (most recent call last):
  File "load.py", line 12, in <module>
    l=pyb.encode(ocbgp)
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 529, in encode
    self._preprocess_element(obj, mode="ietf"))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 532, in default
    return pybindJSONEncoder().default(obj, mode="ietf")
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 137, in default
    val = self.map_pyangbind_type(pyc, orig_yangt, obj, mode)
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 197, in map_pyangbind_type
    return self._preprocess_element(obj.get(), mode=mode)
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 57, in _preprocess_element
    nd[k] = self._preprocess_element(d[k], mode=mode)
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 57, in _preprocess_element
    nd[k] = self._preprocess_element(d[k], mode=mode)
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 57, in _preprocess_element
    nd[k] = self._preprocess_element(d[k], mode=mode)
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 57, in _preprocess_element
    nd[k] = self._preprocess_element(d[k], mode=mode)
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 57, in _preprocess_element
    nd[k] = self._preprocess_element(d[k], mode=mode)
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 61, in _preprocess_element
    nd[k] = self.default(d[k], mode=mode)
  File "/Library/Python/2.7/site-packages/pyangbind/lib/serialise.py", line 161, in default
    type(obj), obj))
AttributeError: Unmapped type: None, None, None, None, <class 'decimal.Decimal'>, 90

**Comment by sanabby** [comment]
The way I am using the API is:

from pprint import pprint
from pyangbind.lib.serialise import pybindIETFJSONEncoder
pyb = pybindIETFJSONEncoder()
oc=openconfig_bgp()
ocbgp = bgp.bgp()
ocbgp.global_.config.as_ = 2856
ocbgp.global_.config.router_id = "10.102.44.72"
ocbgp.neighbors.neighbor.add("192.168.1.2")
ocbgp.neighbors.neighbor["192.168.1.2"].config.peer_as = 5400
ocbgp.neighbors.neighbor["192.168.1.2"].config.description = "a fictional transit session"
oc._set_bgp(ocbgp)
l=pyb.encode(oc)
pprint(l)

 I was getting the exception while calling the encode on pybindIETFJSONEncoder.

**Comment by robshakir** [comment]
Hi!

Did you see the documentation at http://pynms.io/pyangbind/getting_started/ - particularly the "serialising a data instance" section?

If you need to call this directly (without using `dumps` or `dump`), then I'd recommend taking a look here: https://github.com/robshakir/pyangbind/blob/master/pyangbind/lib/pybindJSON.py#L153-L158 

The pybindJSON class isn't designed to called with encode() directly like this, it expects to be called through the `json` library as a custom encoder class.

Let me know if you have other problems!

Thanks,
r.

**Comment by robshakir** [comment]
Ah, apologies, this fails when `filter=False` on this function. Let me check the fix.

**Comment by sanabby** [comment]
I used the pybindJSON.dumps and am fine with it. 

Thanks for adding the fix and test cases for decimal serialization issue
