### ISSUE TITLE
TypeError exception with ietf-netconf-acm

### ISSUE THREAD

**Issue by mathieu-mercier** [robshakir/pyangbind#124]
I get the following error when I try to generate bindings for http://www.netconfcentral.org/modules/ietf-netconf-acm:

pyang --plugindir $PYBINDPLUGIN -f pybind -o binding.py ietf-netconf-acm.yang
could not find a match for nacm:access-operations-type type -> [u'bits']
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 434, in <module>
    run()
  File "/usr/local/bin/pyang", line 408, in run
    emit_obj.emit(ctx, modules, fd)
  File "/usr/local/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 217, in emit
    build_pybind(ctx, modules, fd)
  File "/usr/local/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 395, in build_pybind
    build_typedefs(ctx, defn['typedef'])
  File "/usr/local/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 546, in build_typedefs
    raise TypeError("could not resolve typedefs %s" % error_ids)
TypeError: could not resolve typedefs [u'nacm:access-operations-type']

**Comment by JoseIgnacioTamayo** [comment]
Could you please try again with the latest / recent version of pyangbing, and the latest YANG module?

**Comment by hyberdk** [comment]
Hey @JoseIgnacioTamayo, 

Im facing the same problem it seems like there are still issues.. 

```
(venv) eslau@eslau-mac pyangbind_test % pip list
Package    Version
---------- --------
enum34     1.1.10
lxml       6.0.1
pip        25.1.1
pyang      2.7.1
pyangbind  0.8.6
regex      2025.9.1
setuptools 80.9.0
(venv) eslau@eslau-mac pyangbind_test % python3 --version
Python 3.11.13
(venv) eslau@eslau-mac pyangbind_test % pyang --plugindir $PYBINDPLUGIN -f pybind -o binding.py ietf-netconf-acm@2018-02-14.yang
Traceback (most recent call last):
  File "/Users/eslau/repos/pyangbind_test/venv/bin/pyang", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/eslau/repos/pyangbind_test/venv/lib/python3.11/site-packages/pyang/scripts/pyang_tool.py", line 548, in run
    emit_obj.emit(ctx, modules, fd)
  File "/Users/eslau/repos/pyangbind_test/venv/lib/python3.11/site-packages/pyangbind/plugin/pybind.py", line 203, in emit
    build_pybind(ctx, modules, fd)
  File "/Users/eslau/repos/pyangbind_test/venv/lib/python3.11/site-packages/pyangbind/plugin/pybind.py", line 400, in build_pybind
    build_typedefs(ctx, defn["typedef"])
  File "/Users/eslau/repos/pyangbind_test/venv/lib/python3.11/site-packages/pyangbind/plugin/pybind.py", line 569, in build_typedefs
    cls, elemtype = copy.deepcopy(build_elemtype(ctx, item.search_one("type")))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eslau/repos/pyangbind_test/venv/lib/python3.11/site-packages/pyangbind/plugin/pybind.py", line 1362, in build_elemtype
    pos = 1 + max(allowed_bits)
              ^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
(venv) eslau@eslau-mac pyangbind_test % 

```

is there anything I can do to help?

Esben
