### ISSUE TITLE
No support for anyxml

### ISSUE THREAD

**Issue by mortenthansen** [robshakir/pyangbind#134]
Hi Rob,

Thanks for a great tool. I've been using it for a while but ran into some problems with creating a python binding for the netconf YANG module (RFC6241). This module includes anyxml elements which seems to be unsupported in pyangbind, can you confirm this?

I get the following error and looking at line 1442 in pybind.py it seems that the code assumes that that the element is a leaf when it in fact is an anyxml.

Traceback (most recent call last):
  File "/usr/bin/pyang", line 444, in <module>
    run()
  File "/usr/bin/pyang", line 413, in run
    emit_obj.emit(ctx, modules, fd)
  File "/usr/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 217, in emit
    build_pybind(ctx, modules, fd)
  File "/usr/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 409, in build_pybind
    get_children(ctx, fd, children, m, m)
  File "/usr/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 725, in get_children
    parent_cfg=parent_cfg, choice=choice, register_paths=register_paths)
  File "/usr/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 1442, in get_element
    element.search_one('type')))
  File "/usr/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 1132, in build_elemtype
    pattern_stmt = et.search_one('pattern') if not et.search_one('pattern') \
AttributeError: 'NoneType' object has no attribute 'search_one'

For your convenience I here is a snippet from the netconf YANG module:

anyxml data {
          description
            "Copy of the source datastore subset that matched
             the filter criteria (if any).  An empty data container
             indicates that the request did not produce any results.";
}

Any plans for supporting anyxml elements which seems to be supported in pyang?

**Comment by robshakir** [comment]
Currently, there isn't a plan to support `anyxml`, please feel free to propose a patch.
