### ISSUE TITLE
XPath tests fail with pyang 1.4.1

### ISSUE THREAD

**Issue by marksutherland** [robshakir/pyangbind#19]
I'm seeing the following with the latest master, I have pyang 1.4.1 installed 
```
RUNNING BASE
TESTING /home/msuther/Repositories/pyangbind/tests/xpath/03-current...
/home/msuther/Repositories/pyangbind/tests/xpath/03-current/current-tc03.yang:40: error: current-tc03:referenced in the path's predicate for reference at /home/msuther/Repositories/pyangbind/tests/xpath/03-current/current-tc03.yang:38 is compared with a leaf that is not a correct leafref
FATAL: pyangbind cannot build module that pyang has found errors with.
Traceback (most recent call last):
  File "/home/msuther/Repositories/pyangbind/tests/xpath/03-current/run.py", line 69, in <module>
    main()
  File "/home/msuther/Repositories/pyangbind/tests/xpath/03-current/run.py", line 29, in main
    from bindings import current_tc03
ImportError: No module named bindings
TEST FAILED /home/msuther/Repositories/pyangbind/tests/xpath/03-current
TESTING /home/msuther/Repositories/pyangbind/tests/xpath/01-list_leaflist...
TESTING /home/msuther/Repositories/pyangbind/tests/xpath/02-static_ptr...
RESULT: 1 tests failed
```

```
# pyang --version
pyang 1.4.1
```

Looking at the pyang repository this is actually quite an old version. Is pyang 1.6 a requirement?

**Comment by robshakir** [comment]
Hi Mark,

I've never checked against anything prior to pyang 1.5, so whilst I can't say pyang 1.6 is a requirement, I think I'll say that 1.4 is unsupported. If this happens in 1.5 or 1.6, then please shout.

Cheers,
r.

**Comment by marksutherland** [comment]
It's just the xpath tests that are having issues. I'll see if I can migrate to something newer. Thanks!
