### ISSUE TITLE
pyang bind fails with TypeError on Yang action statement

### ISSUE THREAD

**Issue by nickweeds** [robshakir/pyangbind#210]
If the Yang module contains a Yang 1.1 action statement then pyang bind fails with a TypeError.

For example, running pyang bind on the ietf-routing.yang module in [RFC 8349](https://www.ietf.org/rfc/rfc8349.txt) fails as follows:

    $ pyang --plugindir $PYBINDPLUGIN -f pybind -o ietf-routing.py ietf-routing.yang
    Traceback (most recent call last):
      File "/usr/bin/pyang", line 444, in <module>
        run()
      File "/usr/bin/pyang", line 413, in run
        emit_obj.emit(ctx, modules, fd)
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 203, in emit
        build_pybind(ctx, modules, fd)
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 419, in build_pybind
        get_children(ctx, fd, children, m, m)
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 760, in get_children
        register_paths=register_paths,
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 1456, in get_element
        register_paths=register_paths,
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 760, in get_children
        register_paths=register_paths,
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 1456, in get_element
        register_paths=register_paths,
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 760, in get_children
        register_paths=register_paths,
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 1456, in get_element
        register_paths=register_paths,
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 760, in get_children
        register_paths=register_paths,
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 1456, in get_element
        register_paths=register_paths,
      File "/data/npw/tmp/pyangbind/pyangbind/plugin/pybind.py", line 820, in get_children
        raise TypeError("unhandled keyword with children %s at %s" % (parent.keyword, parent.pos))
    TypeError: unhandled keyword with children action at ietf-routing.yang:469

[This output is from running pyangbind master commit bcb1d8677f4d11e0aca61d658ccab0d48c7b6322]

It would be preferable to ignore action statements and generate the rest of the Python code, or to support action statements in a similar fashion to RPCs.

**Comment by TheCholox** [comment]
I also experienced that problem and did a quick and dirty fix. [See here.
](https://github.com/TheCholox/pyangbind)You just need to add `action` to a specific list. ([here is the required addition](https://github.com/TheCholox/pyangbind/commit/2fdc3cea7801656782a07d214ef625820dcefd74#diff-693d7d91d09ea3fadf56bd008f81566e))

I know this is a dirty fix, but the generation works and the actions are ignored (empty classes are created).

**Comment by JoseIgnacioTamayo** [comment]
Updated the Title of the issue.
