### ISSUE TITLE
Serializing leaf-list error

### ISSUE THREAD

**Issue by paulinaalvarez** [robshakir/pyangbind#246]
There is an issue while serializing leaf-list.

I have an example using the openconfig model of network-instance, the field enabled-address-families, defined in:
https://github.com/openconfig/public/blob/8527e6426cf136930ff24f60939994949cefc073/release/models/network-instance/openconfig-network-instance-l3.yang#L129

I got the following code:
```
from pyangbind.lib.serialise import pybindIETFXMLDecoder, pybindIETFXMLEncoder
import pyangbind_classes.network_instance as oc_network_instance

data = """
<openconfig-network-instances xmlns="http://openconfig.net/yang/network-instance">
    <network-instances xmlns="http://openconfig.net/yang/network-instance">
        <network-instance>
          <name>default</name>
          <config>
            <enabled-address-families>IPV4</enabled-address-families>
            <enabled-address-families>IPV6</enabled-address-families>
            <name>default</name>
            <type>DEFAULT_INSTANCE</type>
          </config>
        </network-instance>
    </network-instances>
</openconfig-network-instances>
"""

obj = pybindIETFXMLDecoder().decode(data, oc_network_instance, "openconfig_network_instance")
obj_xml = pybindIETFXMLEncoder.serialise(obj)
print(obj_xml)
```

Gives an error, here the traceback:
```
Traceback (most recent call last):
  File "/home/palvarez/dev/test/test.py", line 22, in <module>
    obj_xml = pybindIETFXMLEncoder.serialise(obj)
  File "/home/palvarez/dev/.venv2/lib/python3.6/site-packages/pyangbind/lib/serialise.py", line 380, in serialise
    doc = cls.encode(obj, filter=filter)
  File "/home/palvarez/dev/.venv2/lib/python3.6/site-packages/pyangbind/lib/serialise.py", line 373, in encode
    tree = ietf_tree_xml_func(obj, flt=filter)
  File "/home/palvarez/dev/.venv2/lib/python3.6/site-packages/pyangbind/lib/serialise.py", line 422, in generate_ietf_tree
    element, parent_namespace=element._namespace, flt=flt, with_defaults=with_defaults
  File "/home/palvarez/dev/.venv2/lib/python3.6/site-packages/pyangbind/lib/serialise.py", line 429, in generate_ietf_tree
    for i in element.itervalues()
  File "/home/palvarez/dev/.venv2/lib/python3.6/site-packages/pyangbind/lib/serialise.py", line 429, in <listcomp>
    for i in element.itervalues()
  File "/home/palvarez/dev/.venv2/lib/python3.6/site-packages/pyangbind/lib/serialise.py", line 422, in generate_ietf_tree
    element, parent_namespace=element._namespace, flt=flt, with_defaults=with_defaults
  File "/home/palvarez/dev/.venv2/lib/python3.6/site-packages/pyangbind/lib/serialise.py", line 417, in generate_ietf_tree
    yname = yname_ns_func(parent_namespace, element, yname)
  File "/home/palvarez/dev/.venv2/lib/python3.6/site-packages/pyangbind/lib/serialise.py", line 365, in yname_ns_func
    (element._enumeration_dict[element]["@module"], element._enumeration_dict[element]["@namespace"])
AttributeError: 'YANGBaseClass' object has no attribute '_enumeration_dict'
```

There is no problem when deserializing the XML, the attribute is created correctly. But when trying to serialize it back, the exact same object, it fails.

I added to the condition causing the problem 'and not hasattr(element, "_list")', which is the only thing I could come up with.
https://github.com/robshakir/pyangbind/blob/9aaf5339bf8226bed7f75190e781783f1760e039/pyangbind/lib/serialise.py#L362

Does anyone have a better solution? Can someone check it out?

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Could you please try again with recent versions of pyangbind?

Thanks.
