### ISSUE TITLE
pyangbind does not cope with nested choices inside cases

### ISSUE THREAD

**Issue by andrew-lee-metaswitch** [robshakir/pyangbind#258]
Using Schema:

```
module example {
  yang-version 1.1;
  namespace "http://example.com/20190904";
  prefix example;

  organization
    "Example";
  contact
    "me";
  description
    "Example";

  revision 2019-09-04 {
    description
      "Initial revision";
    reference
      "Me";
  }

  container a-choice {
    choice foo {
      case foo-a {
        description
          "foo";
        choice bar {
          case bar-a {
            leaf bar-a-conf {
              type string;
            }
          }
          case bar-b {
            leaf bar-b-conf {
              type string;
            }
          }
        }
      }
      case foo-b {
        description
          "foo";
        choice baz {
          case baz-a {
            leaf baz-a-conf {
              type string;
            }
          }
          case baz-b {
            leaf baz-b-conf {
              type string;
            }
          }
        }
      }
    }
  }
}
```

Running 

> pyang --path ietf:schema --plugindir pyangbind/plugin --format pybind --use-xpathhelper schema/example.yang 

I get the following error: 

```
Traceback (most recent call last):
  File "/data/developer/.virtualenvs/sas-demo/bin/pyang", line 493, in <module>
    run()
  File "/data/developer/.virtualenvs/sas-demo/bin/pyang", line 462, in run
    emit_obj.emit(ctx, modules, fd)
  File "/data/developer/.virtualenvs/sas-demo/lib/python3.6/site-packages/pyangbind/plugin/pybind.py", line 204, in emit
    build_pybind(ctx, modules, fd)
  File "/data/developer/.virtualenvs/sas-demo/lib/python3.6/site-packages/pyangbind/plugin/pybind.py", line 421, in build_pybind
    get_children(ctx, fd, children, m, m)
  File "/data/developer/.virtualenvs/sas-demo/lib/python3.6/site-packages/pyangbind/plugin/pybind.py", line 762, in get_children
    register_paths=register_paths,
  File "/data/developer/.virtualenvs/sas-demo/lib/python3.6/site-packages/pyangbind/plugin/pybind.py", line 1465, in get_element
    register_paths=register_paths,
  File "/data/developer/.virtualenvs/sas-demo/lib/python3.6/site-packages/pyangbind/plugin/pybind.py", line 747, in get_children
    register_paths=register_paths,
  File "/data/developer/.virtualenvs/sas-demo/lib/python3.6/site-packages/pyangbind/plugin/pybind.py", line 1465, in get_element
    register_paths=register_paths,
  File "/data/developer/.virtualenvs/sas-demo/lib/python3.6/site-packages/pyangbind/plugin/pybind.py", line 762, in get_children
    register_paths=register_paths,
  File "/data/developer/.virtualenvs/sas-demo/lib/python3.6/site-packages/pyangbind/plugin/pybind.py", line 1465, in get_element
    register_paths=register_paths,
  File "/data/developer/.virtualenvs/sas-demo/lib/python3.6/site-packages/pyangbind/plugin/pybind.py", line 822, in get_children
    raise TypeError("unhandled keyword with children %s at %s" % (parent.keyword, parent.pos))
TypeError: unhandled keyword with children case at schema/example.yang:26
```

However, with no nested cases, this works and pyangbind works:

```
module example {
  yang-version 1.1;
  namespace "http://example.com/20190904";
  prefix example;

  organization
    "Example";
  contact
    "me";
  description
    "Example";

  revision 2019-09-04 {
    description
      "Initial revision";
    reference
      "Me";
  }

  container a-choice {
    choice foo {
      case foo-a {
        description
          "foo";
        leaf foo-a-conf {
          type string;
        }
      }
      case foo-b {
        description
          "foo";
        leaf foo-b-conf {
          type string;
        }
      }
    }
  }
}
```

**Comment by gusmb** [comment]
Getting the same issue when trying to generate bindings for Cisco IOS-XE native model
`pyang --plugindir $PYBINDPLUGIN -f pybind -o cisco_ios_xe.py Cisco-IOS-XE-native.yang -p ../../../../standard/ietf/RFC:.`
Error:
`
 File "/home/lab/Downloads/venv/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 742, in get_children
    parent_cfg=parent_cfg, choice=choice, register_paths=register_paths)
  File "/home/lab/Downloads/venv/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 1408, in get_element
    choice=choice, register_paths=register_paths)
  File "/home/lab/Downloads/venv/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 801, in get_children
    (parent.keyword, parent.pos))
TypeError: unhandled keyword with children case at Cisco-IOS-XE-native.yang:2162 (at Cisco-IOS-XE-ip.yang:258)
 File "/home/lab/Downloads/venv/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 742, in get_children
    parent_cfg=parent_cfg, choice=choice, register_paths=register_paths)
  File "/home/lab/Downloads/venv/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 1408, in get_element
    choice=choice, register_paths=register_paths)
  File "/home/lab/Downloads/venv/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 801, in get_children
    (parent.keyword, parent.pos))
TypeError: unhandled keyword with children case at Cisco-IOS-XE-native.yang:2162 (at Cisco-IOS-XE-ip.yang:258)
`

**Comment by amoruck** [comment]
Same for me, huawei-acl.yang 
  File "/opt/envs/acl/lib64/python3.6/site-packages/pyangbind/plugin/pybind.py", line 801, in get_children
    (parent.keyword, parent.pos))
TypeError: unhandled keyword with children case at ../models/huawei-acl.yang:1115

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Could you please try again with recent versions of pyangbind?

Thanks.

**Comment by Pabloandag** [comment]
Hi @JoseIgnacioTamayo!, 
I'm facing the same issue with version v0.8.1.post1

**Comment by JoseIgnacioTamayo** [comment]
I think https://github.com/robshakir/pyangbind/tree/fix_nested_choice has a solution.

@Pabloandag , could you try with this branch, before I propose a PullRequest ?

**Comment by JoseIgnacioTamayo** [comment]
Fixing in https://github.com/robshakir/pyangbind/pull/340

**Comment by JoseIgnacioTamayo** [comment]
https://github.com/robshakir/pyangbind/pull/340 was merged and included in https://github.com/robshakir/pyangbind/releases/tag/0.8.5

Considering this issue fixed. Please re-open if not.
