### ISSUE TITLE
Issue running pyangbind class generation plugin

### ISSUE THREAD

**Issue by mpainenz** [robshakir/pyangbind#37]
Hi Rob,

I feel like I'm missing something very simple at this end. I just did a pull from the Master branch, and tried to generate my Class Bindings. 

I get the following error message now:

```
Running: python C:\Python\Libraries\pyang\bin\pyang --plugindir C:\Python\Libraries\pyangbind -f pybind C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\sbc-common.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\signaling-firewall.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\system.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\feature-profiles.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\rate-limiting.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\vnets.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\media.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\message-manipulation.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\call-admission-control.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\fmm.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\signaling-firewall.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\realms.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\call-routing.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\sip.yang C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\acs-yang\endpoints.yang
Traceback (most recent call last):
  File "C:\Python\Libraries\pyang\bin\pyang", line 425, in <module>
    run()
  File "C:\Python\Libraries\pyang\bin\pyang", line 30, in run
    plugin.init(plugindirs)
  File "C:\Projects\git\genband-oneems-service\.venv\lib\site-packages\pyang\plugin.py", line 37, in init
    pluginmod = __import__(fname[:-3])
  File "C:\Python\Libraries\pyangbind\pybind.py", line 1, in <module>
    Pyangbind/plugin/pybind.py
NameError: name 'Pyangbind' is not defined
```

This is a Windows 10, Python 2.7.11 installation. 

Any ideas?

**Comment by robshakir** [comment]
I'm not 100% sure, as I've never used Python on Windows. You may want to try `--plugindir <path-to-master>/pyangbind/plugin` simply because `pybind.py` in the root of master is a symlink, and I'm really not sure what Windows will do with that (pyang on OS X does not follow the symlink).

r.

**Comment by mpainenz** [comment]
Hi Rob,

That has worked. I think someone who is new to the Plugin would probably have tried that, as the readme does state to point to the plugin directory.

Thanks again for your help.

**Comment by robshakir** [comment]
No problems, thanks for checking.

In the future, I'll remove these symlinks to remove ambiguity - but right now, I have some tooling that needs them.

r.
