### ISSUE TITLE
Yang bits built-in type

### ISSUE THREAD

**Issue by mpainenz** [robshakir/pyangbind#57]
Hi Rob,

I came across a Yang module that uses the[ 'bits' built-in Yang type.](https://tools.ietf.org/html/rfc6020#section-9.7)

Is this currently supported/implemented?

On that note, I wonder if it might be worth adding to the readme somewhere the currently supported/unsupported Yang features. (Sorry if I've missed that somewhere).

Here is a sample of some 'bits' yang...

```
module test {

  namespace "http://test.com/test";
  prefix "test";

  typedef NacmAccessOperationsType {
    type bits {
      bit create {
        position "0";
      }
      bit read {
        position "1";
      }
      bit update {
        position "2";
      }
      bit delete {
        position "3";
      }
      bit exec {
        position "4";
      }
    }
  }
}
```

If bits is supported, I'm having the following issue when I try to generate class bindings. Program output:

```
Pyangbind Version: 0.1.1
Running: python C:\Python\Libraries\pyang\bin\pyang --plugindir C:\Python\Libraries\pyangbind\pyangbind\plugin -f pybind C:\Projects\git\genband-oneems-service\doc\genview_1.0\yang\model\test.yang
[(0, 255)]
[(0, 65535)]
[(0, 4294967295L)]
[(0L, 18446744073709551615L)]
[(-127, 127)]
[(-32767, 32767)]
[(-2147483647, 2147483647)]
[(-9223372036854775807L, 9223372036854775807L)]

from operator import attrgetter
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType, RestrictedClassType, TypedListType
from pyangbind.lib.yangtypes import YANGBool, YANGListType, YANGDynClass, ReferenceType
from pyangbind.lib.base import PybindBase
from decimal import Decimal
from bitarray import bitarray
could not find a match for test:NacmAccessOperationsType type -> [u'bits']
could not find a match for NacmAccessOperationsType type -> [u'bits']
Traceback (most recent call last):
  File "C:\Python\Libraries\pyang\bin\pyang", line 434, in <module>
    run()
  File "C:\Python\Libraries\pyang\bin\pyang", line 408, in run
    emit_obj.emit(ctx, modules, fd)
  File "C:\Python\Libraries\pyangbind\pyangbind\plugin\pybind.py", line 205, in emit
    build_pybind(ctx, modules, fd)
  File "C:\Python\Libraries\pyangbind\pyangbind\plugin\pybind.py", line 361, in build_pybind
    build_typedefs(ctx, defn['typedef'])
  File "C:\Python\Libraries\pyangbind\pyangbind\plugin\pybind.py", line 542, in build_typedefs
    raise TypeError("could not resolve typedefs %s" % error_ids)
TypeError: could not resolve typedefs [u'test:NacmAccessOperationsType', u'NacmAccessOperationsType']

Process finished with exit code 0
```

Rob, I notice that my program output is printing some odd values at the start prior to outputting the class bindings, is there some debug code which has been left in the current master branch?

Cheers,
Mark

**Comment by mpainenz** [comment]
Please ignore the line as follows:

`Pyangbind Version: 0.1.1`

That should read 0.5.0. That 0.1.1 value came from the init.py inside the lib folder

**Comment by robshakir** [comment]
`bits` is not supported currently -- see https://github.com/robshakir/pyangbind/blob/master/docs/yang.md which describes how PyangBind deals with YANG features.

I've removed the debugging cruft, thanks for picking this up.

r.

**Comment by mpainenz** [comment]
Thanks Rob, no worries
