### ISSUE TITLE
Unable to serialize leafs with 'decimal64' type

### ISSUE THREAD

**Issue by lgifre** [robshakir/pyangbind#72]
Hi,

I'm developing an app using pyangbind and I found a problem with the serialization of decimal64 leafs.

Example Model:
```
module test {
	namespace "urn:test:test";
	prefix t;
	typedef Interval { type decimal64 { fraction-digits 2; } }
	container cont { leaf period { type Interval; default "0"; } }
}
```

I'm generating the binding python module by running:
```
export PYBINDPLUGIN=`/usr/bin/env python -c 'import pyangbind; import os; print "%s/plugin" % os.path.dirname(pyangbind.__file__)'`
pyang --plugindir $PYBINDPLUGIN -f pybind -o test.py test.yang
```
And the test app in python:
```
from test import test
import pyangbind.lib.pybindJSON as pybindJSON
t = test()
t.cont.period = 1
pybindJSON.dump(t, 'output.json', filter=False, mode="ietf")
```

When I run the app with:
```
python Main.py
```

Next exception is thrown:
```
Traceback (most recent call last):
  File "Main.py", line 8, in <module>
    pybindJSON.dump(t, 'output.json', filter=False, mode="ietf")
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/pybindJSON.py", line 168, in dump
    skip_subtrees=skip_subtrees, mode=mode))
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/pybindJSON.py", line 158, in dumps
    return json.dumps(tree, cls=cls, indent=indent)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/serialise.py", line 489, in encode
    self._preprocess_element(obj, mode="ietf"))
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/serialise.py", line 54, in _preprocess_element
    nd[k] = self._preprocess_element(d[k], mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/serialise.py", line 58, in _preprocess_element
    nd[k] = self.default(d[k], mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/serialise.py", line 492, in default
    return pybindJSONEncoder().default(obj, mode="ietf")
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/serialise.py", line 156, in default
    type(obj), obj))
AttributeError: Unmapped type: period, Interval, RestrictedPrecisionDecimal, RestrictedPrecisionDecimal, <class 'pyangbind.lib.yangtypes.YANGBaseClass'>, 1.00
```

If I modify the YANG module replacing `type decimal64 { fraction-digits 2; }` by `type uint32` and regenerate the binding module the app works as expected.

Am I doing something wrong or is it a bug in pyangbind?

Thanks in advance!
Lluis

**Comment by robshakir** [comment]
Hi Lluis,

This was a bug - the specific case where there was a `typedef` that included a `decimal64` was unhandled in the code. The latest commit (referencing this issue) resolves this problem. I'll bump versions and upload to this to PyPi.

Apologies for the inconvenience and thanks for the detailed bug report.

Thanks,
r.

**Comment by robshakir** [comment]
Version `0.5.4` has been pushed to PyPi which resolves this issue.

r.

**Comment by lgifre** [comment]
Hi Rob,
Thanks! It works perfectly!
Lluis
