### ISSUE TITLE
[bug] Unmapped type Exception in serialization when "range" is specified in a typedef

### ISSUE THREAD

**Issue by lgifre** [robshakir/pyangbind#78]
Hi Rob!

I'm running some more tests in my app, and found a bug when serializing a typedef with type "decimal64". I'm running pyang v1.7 and pyangbind v0.5.5.

Example model:
```
module test {
    namespace "urn:test:test";
    prefix t;
	typedef BitRateGbps { type decimal64 { fraction-digits 10; range "1 .. max"; } }
    container cont { leaf value { type BitRateGbps; } }
}
```

I'm generating the bindings with:
```
export PYBINDPLUGIN=`/usr/bin/env python -c 'import pyangbind; import os; print "%s/plugin" % os.path.dirname(pyangbind.__file__)'`
pyang --plugindir $PYBINDPLUGIN -f pybind -o test.py test.yang
```

And the app to reproduce the bug:
```
from test import test
import pyangbind.lib.pybindJSON as pybindJSON
t = test()
t.cont.value = 1
pybindJSON.dump(t, 'output.json', filter=False, mode="ietf")
```

This app throws the next Exception:
```
Traceback (most recent call last):
  File "./app.py", line 6, in <module>
    pybindJSON.dump(t, 'output.json', filter=False, mode="ietf")
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/pybindJSON.py", line 168, in dump
    skip_subtrees=skip_subtrees, mode=mode))
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/pybindJSON.py", line 158, in dumps
    return json.dumps(tree, cls=cls, indent=indent)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/serialise.py", line 506, in encode
    self._preprocess_element(obj, mode="ietf"))
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/serialise.py", line 54, in _preprocess_element
    nd[k] = self._preprocess_element(d[k], mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/serialise.py", line 58, in _preprocess_element
    nd[k] = self.default(d[k], mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/serialise.py", line 509, in default
    return pybindJSONEncoder().default(obj, mode="ietf")
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/serialise.py", line 158, in default
    type(obj), obj))
AttributeError: Unmapped type: value, BitRateGbps, decimal.Decimal, decimal.Decimal, <class 'pyangbind.lib.yangtypes.YANGBaseClass'>, 1
```

If you comment/remove the "range" statement in the typedef it works file.
Could you check it, please?
TIA!
Lluis

**Comment by robshakir** [comment]
Thanks for reporting this Lluis, it looks like this was something that was not covered in the tests. I fixed it and added test coverage for it.

Thanks again!
r.
