### ISSUE TITLE
Setting neighbor-address to zoned IP fails.

### ISSUE THREAD

**Issue by jta** [robshakir/pyangbind#83]
Hi,

I'm trying to set a link local IPv6 address to be the neighbor-address for a BGP session. It barfs on set with a regexp that on the surface seems to accept an arbitrary interface:

```
bgp = binding.openconfig_bgp().bgp
>>> neighbor = bgp.neighbors.neighbor.add('fe80::1%vlan100')
>>> neighbor.get(filter=True)
{'neighbor-address': u'fe80::1%vlan100'}
>>> neighbor.config.neighbor_address = neighbor.neighbor_address
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netconfig/openconfig/binding.py", line 44541, in _set_neighbor_address
    'generated-type': """YANGDynClass(base=[RestrictedClassType(base_type=unicode, restriction_dict={'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}),RestrictedClassType(base_type=unicode, restriction_dict={'pattern': u'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'}),], is_leaf=True, yang_name="neighbor-address", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://openconfig.net/yang/bgp', defining_module='openconfig-bgp', yang_type='inet:ip-address', is_config=True)""",
ValueError: {'error-string': 'neighbor_address must be of a type compatible with inet:ip-address', 'generated-type': 'YANGDynClass(base=[RestrictedClassType(base_type=unicode, restriction_dict={\'pattern\': u\'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?\'}),RestrictedClassType(base_type=unicode, restriction_dict={\'pattern\': u\'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?\'}),], is_leaf=True, yang_name="neighbor-address", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace=\'http://openconfig.net/yang/bgp\', defining_module=\'openconfig-bgp\', yang_type=\'inet:ip-address\', is_config=True)', 'defined-type': 'inet:ip-address'}
```

The fact that any attempt to set `config.neighbor-address = neighbor-address` would fail is odd, since I'd expect the validation to be the same. On further inspection it doesn't seem that keys are validated at all:

```
>>> bgp.neighbors.neighbor.add('test').get(filter=True)
{'neighbor-address': u'test'}
```

Is this expected?

**Comment by robshakir** [comment]
Hi!

The second part of this issue is a nuance of how OpenConfig works -- the `neighbor-address` leaf that is the key is actually a leafref. If you are running pyangbind without `--use-xpathhelper` and/or have not specified a `path_helper` when initialising the classes, then `leafref` simply acts like a string. As the key is (withouth a `path_helper`) a string, then it is possible to set it to anything. Example:

```python
>>> from ocbind import openconfig_bgp
>>> from pyangbind.lib.xpathhelper import YANGPathHelper
>>> p = YANGPathHelper()
>>> b = openconfig_bgp(path_helper=p)
>>> b.bgp.neighbors.neighbor.add("test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rjs/Code/pyangbind/pyangbind/lib/yangtypes.py", line 716, in add
    self.__set(_k=k)
  File "/Users/rjs/Code/pyangbind/pyangbind/lib/yangtypes.py", line 641, in __set
    raise KeyError("key value must be valid, %s" % m)
KeyError: 'key value must be valid, {\'error-string\': \'neighbor_address must be of a type compatible with leafref\', \'generated-type\': \'YANGDynClass(base=ReferenceType(referenced_path=\\\'../config/neighbor-address\\\', caller=self._path() + [\\\'neighbor-address\\\'], path_helper=self._path_helper, require_instance=True), is_leaf=True, yang_name="neighbor-address", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace=\\\'http://openconfig.net/yang/bgp\\\', defining_module=\\\'openconfig-bgp\\\', yang_type=\\\'leafref\\\', is_config=True)\', \'defined-type\': \'leafref\'}'
```

The problem with "fe80::1%vlan100" appears to be that Python `re` does not use \p{N} or \p{L} that are used in the regexp to express a zone. Let me look into what we can do about that - there is a method in `lib.yangtypes` that could be used to convert those if they are really not supported.

Cheers,
r.

**Comment by JoseIgnacioTamayo** [comment]
Closing issues without recent activity
